version: 0.2

env:
  variables:
SITEBUILD: "yes"
phases:
  install:
commands:
apt-get update -y
  pre_build:
commands:
gem install jekyll bundler
bundle install
  build:
commands:
echo Build started on date
bundle exec jekyll build
aws s3 sync _site/ s3://phillytech-jekylltest1
  post_build:
commands:
echo Build completed on date
